import React, { useState } from 'react';
import { AppMode } from './types';
import CameraInterface from './components/CameraInterface';
import CodeViewer from './components/CodeViewer';
import { VideoCameraIcon, CodeBracketIcon, BookOpenIcon } from '@heroicons/react/24/solid';

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<AppMode>(AppMode.DEMO);

  return (
    <div className="min-h-screen bg-cv-dark flex flex-col text-gray-100 font-sans selection:bg-cv-accent selection:text-black">
      {/* Header */}
      <header className="border-b border-gray-800 bg-cv-panel/50 backdrop-blur-md sticky top-0 z-50">
        <div className="max-w-7xl mx-auto px-4 h-16 flex items-center justify-between">
          <div className="flex items-center gap-3">
            <div>
               <h1 className="font-bold text-lg tracking-tight text-white">Intelligent Border Surveillance System</h1>
               <div className="text-[10px] font-mono text-cv-accent uppercase tracking-widest">SAM 3 Camera Vision Portfolio</div>
            </div>
          </div>

          <nav className="flex items-center bg-gray-900/50 p-1 rounded-lg border border-gray-700/50">
            <TabButton 
              active={activeTab === AppMode.DEMO} 
              onClick={() => setActiveTab(AppMode.DEMO)}
              icon={<VideoCameraIcon className="w-4 h-4" />}
              label="Live Demo"
            />
            <TabButton 
              active={activeTab === AppMode.CODE} 
              onClick={() => setActiveTab(AppMode.CODE)}
              icon={<CodeBracketIcon className="w-4 h-4" />}
              label="Source Code"
            />
             <TabButton 
              active={activeTab === AppMode.README} 
              onClick={() => setActiveTab(AppMode.README)}
              icon={<BookOpenIcon className="w-4 h-4" />}
              label="Docs"
            />
          </nav>
        </div>
      </header>

      {/* Main Content */}
      <main className="flex-1 flex flex-col relative">
        <div className="absolute inset-0 bg-[url('https://grainy-gradients.vercel.app/noise.svg')] opacity-20 pointer-events-none"></div>
        
        <div className="relative z-10 flex-1 py-6">
          {activeTab === AppMode.DEMO && (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <CameraInterface />
            </div>
          )}
          
          {activeTab === AppMode.CODE && (
            <div className="animate-in fade-in slide-in-from-bottom-4 duration-500">
              <CodeViewer />
            </div>
          )}

          {activeTab === AppMode.README && (
             <div className="animate-in fade-in slide-in-from-bottom-4 duration-500 max-w-4xl mx-auto p-8 bg-cv-panel rounded-xl border border-gray-700 shadow-2xl">
                <article className="prose prose-invert prose-blue max-w-none">
                  {/* We just render a friendly view of the markdown content here for the 'Docs' tab, 
                      reusing the constant but rendering it simply */}
                  <h1>Intelligent Border Surveillance System</h1>
                  <p className="lead text-xl text-gray-300">
                    A high-performance Python application integrating Segment Anything Model 3 (SAM 3) 
                    with OpenCV for real-time webcam segmentation.
                  </p>
                  
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-6 my-8 not-prose">
                     <FeatureCard title="30 FPS" desc="Optimized for real-time performance on mid-range GPUs." />
                     <FeatureCard title="Dual Modes" desc="Auto-segmentation and interactive point-prompting." />
                     <FeatureCard title="OpenCV" desc="Robust camera handling and visualization pipeline." />
                  </div>

                  <h3>Quick Start</h3>
                  <div className="bg-black p-4 rounded-lg font-mono text-sm border-l-4 border-cv-accent">
                    pip install -r requirements.txt<br/>
                    python sam3_camera.py
                  </div>

                  <p className="text-sm text-gray-400 mt-8">
                    To view the full README and source code, switch to the <strong>Source Code</strong> tab.
                  </p>
                </article>
             </div>
          )}
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-gray-800 bg-gray-900/50 py-4">
         <div className="max-w-7xl mx-auto px-4 text-center text-xs text-gray-500 font-mono">
           Intelligent Border Surveillance System • Generated by AI • React + TypeScript + Gemini
         </div>
      </footer>
    </div>
  );
};

const TabButton: React.FC<{ active: boolean; onClick: () => void; icon: React.ReactNode; label: string }> = ({ active, onClick, icon, label }) => (
  <button
    onClick={onClick}
    className={`flex items-center gap-2 px-4 py-2 rounded-md text-sm font-medium transition-all duration-200 ${
      active 
        ? 'bg-cv-panel text-white shadow-sm ring-1 ring-white/10' 
        : 'text-gray-400 hover:text-white hover:bg-gray-800'
    }`}
  >
    {icon}
    {label}
  </button>
);

const FeatureCard: React.FC<{ title: string; desc: string }> = ({ title, desc }) => (
  <div className="bg-gray-800/50 p-4 rounded-lg border border-gray-700">
    <div className="text-cv-accent font-bold mb-1">{title}</div>
    <div className="text-sm text-gray-400">{desc}</div>
  </div>
);

export default App;