apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: astraguard
  namespace: astraguard
spec:
  host: astraguard-astra-guard.astraguard.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        http1MaxPendingRequests: 100
    outlierDetection:
      consecutive5xxErrors: 5
      interval: 10s
      baseEjectionTime: 30s
